name: zana_storage
description: A inventory application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  get_storage: ^1.3.2
  get: ^3.22.2
  http: ^0.12.2
  equatable: ^1.2.5
  either_type: ^0.1.2
  json_serializable: ^3.5.1
  qrscan: ^0.2.21
  flutter_spinkit: ^4.1.2+1
  permission_handler: ^5.0.1+1
  flutter_boom_menu: ^1.0.2
  circular_check_box: ^1.0.4
  flutter_screenutil: ^4.0.2+3
  flutter_downloader: ^1.5.2
  downloads_path_provider_28: ^0.1.0
  flutter_svg: ^0.19.0
  auto_size_text: ^2.1.0
  flutter_xlider: ^3.4.0
  image_picker: 0.6.0+17
  image_cropper: 1.0.2
  multipart_request: ^0.3.1
  flutter_native_image: ^0.0.5+3
#  downloads_path_provider: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
